[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
  [plugins.inputs.settings]
    locale = "id" # generates Lighthouse reports in indonesia
