[build]
  publish = "publish"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    output_path = "publish/reports/lighthouse.html" 

  [plugins.inputs.settings]
    locale = "id"
